#import "JGStrings.h"

static NSDictionary<NSString *, NSString *> *JGEnglishStrings(void) {
    static NSDictionary *table; static dispatch_once_t onceToken; dispatch_once(&onceToken, ^{ table=@{
        @"section.ghost": @"Ghost Mode",
        @"section.messages": @"Messages",
        @"section.protected": @"Protected Content",
        @"section.stories": @"Stories / Media",
        @"section.profile": @"Profile",
        @"section.appearance": @"Appearance",
        @"section.other": @"Other",
        @"section.about": @"About",
        @"about.jerkgram": @"Jerkgram 1.0.2",
        @"about.base": @"Telegram 12.9.4",
        @"about.account": @"Account scope",
        @"boost.off": @"Off",
        @"boost.medium": @"Medium",
        @"boost.maximum": @"Maximum",
        @"action.cancel": @"Cancel",
        @"action.save": @"Save",
        @"value.enter": @"Enter value",
        @"setting.GhostMode_ReadMessages": @"Do not send read receipts",
        @"setting.GhostMode_TypingActions": @"Hide typing",
        @"setting.GhostMode_HideRecording": @"Hide recording activity",
        @"setting.GhostMode_HideUploading": @"Hide upload activity",
        @"setting.GhostMode_HideStickerActivity": @"Hide sticker activity",
        @"setting.GhostMode_HideGameActivity": @"Hide game activity",
        @"setting.GhostMode_HideEmojiActivity": @"Hide emoji activity",
        @"setting.GhostMode_Presence": @"Hide online presence",
        @"setting.GhostMode_ScheduledSend": @"Scheduled send privacy",
        @"setting.Messages_SaveDeleted": @"Save deleted messages",
        @"setting.Messages_ShowDeleted": @"Show deleted messages",
        @"setting.Messages_SaveEditHistory": @"Save edit history",
        @"setting.Messages_ShowEditHistory": @"Show edit history",
        @"setting.Messages_HideBlockedMessages": @"Hide blocked-user messages",
        @"setting.Messages_HideBlockedReactions": @"Hide blocked-user reactions",
        @"setting.Messages_SendTextStyle": @"Send text style",
        @"setting.Messages_DeletedPortableReplies": @"Portable replies to deleted messages",
        @"setting.Messages_PreserveDeletedMedia": @"Preserve deleted media",
        @"setting.Messages_DeletedMediaCacheLimit": @"Deleted media cache limit",
        @"setting.Messages_DeletedMediaRetentionDays": @"Deleted media retention (days)",
        @"setting.Messages_ForwardWithoutAuthor": @"Forward without author",
        @"setting.ProtectedContent_Enabled": @"Protected content tools",
        @"setting.ProtectedContent_GalleryShare": @"Gallery sharing",
        @"setting.ProtectedContent_GallerySave": @"Gallery saving",
        @"setting.ProtectedContent_GalleryCopy": @"Gallery copying",
        @"setting.ProtectedContent_ChatSave": @"Chat saving",
        @"setting.ProtectedContent_ChatCopy": @"Chat copying",
        @"setting.ProtectedContent_ChatForward": @"Chat forwarding",
        @"setting.ProtectedContent_AllowScreenshots": @"Allow screenshots",
        @"setting.ProtectedContent_AllowScreenRecording": @"Allow screen recording",
        @"setting.ProtectedContent_OneTimeScreenshots": @"View-once screenshots",
        @"setting.ProtectedContent_OneTimeScreenRecording": @"View-once screen recording",
        @"setting.ProtectedContent_OneTimeSave": @"Save view-once media",
        @"setting.Stories_Save": @"Save stories",
        @"setting.Profile_Enabled": @"Profile enhancements",
        @"setting.Profile_ShowIds": @"Show IDs",
        @"setting.Profile_ShowDCs": @"Show data centers",
        @"setting.Profile_ShowRegistration": @"Show registration info",
        @"setting.Appearance_ShowRamUnderClock": @"Show RAM under clock",
        @"setting.Appearance_MessageSeconds": @"Show message seconds",
        @"setting.Appearance_HideOwnPhone": @"Hide own phone number",
        @"setting.Glass_Enabled": @"Glass interface",
        @"setting.ProfileBlur_Avatar": @"Avatar profile background",
        @"setting.ProfileBlur_Animated": @"Animated profile background",
        @"setting.ProfileBlur_Tint": @"Profile background tint",
        @"setting.ProfileBlur_Reduced": @"Reduced profile blur",
        @"setting.Stars_LocalBalance_Enabled": @"Local Stars balance",
        @"setting.Stars_LocalBalance_Amount": @"Local Stars amount",
        @"setting.Stars_LocalBalance_BaseAmount": @"Base Stars amount",
        @"setting.global_DownloadBoost": @"Download Boost",
    }; }); return table;
}
static NSDictionary<NSString *, NSString *> *JGRussianStrings(void) {
    static NSDictionary *table; static dispatch_once_t onceToken; dispatch_once(&onceToken, ^{ table=@{
        @"section.ghost": @"Ghost Mode",
        @"section.messages": @"Сообщения",
        @"section.protected": @"Защищённый контент",
        @"section.stories": @"Истории / Медиа",
        @"section.profile": @"Профиль",
        @"section.appearance": @"Внешний вид",
        @"section.other": @"Другое",
        @"section.about": @"О клиенте",
        @"about.jerkgram": @"Jerkgram 1.0.2",
        @"about.base": @"Telegram 12.9.4",
        @"about.account": @"Область аккаунта",
        @"boost.off": @"Выкл.",
        @"boost.medium": @"Среднее",
        @"boost.maximum": @"Максимум",
        @"action.cancel": @"Отмена",
        @"action.save": @"Сохранить",
        @"value.enter": @"Введите значение",
        @"setting.GhostMode_ReadMessages": @"Не отправлять отметки о прочтении",
        @"setting.GhostMode_TypingActions": @"Скрывать набор текста",
        @"setting.GhostMode_HideRecording": @"Скрывать запись",
        @"setting.GhostMode_HideUploading": @"Скрывать загрузку",
        @"setting.GhostMode_HideStickerActivity": @"Скрывать выбор стикера",
        @"setting.GhostMode_HideGameActivity": @"Скрывать игровую активность",
        @"setting.GhostMode_HideEmojiActivity": @"Скрывать эмодзи-активность",
        @"setting.GhostMode_Presence": @"Скрывать онлайн-статус",
        @"setting.GhostMode_ScheduledSend": @"Приватность отложенной отправки",
        @"setting.Messages_SaveDeleted": @"Сохранять удалённые сообщения",
        @"setting.Messages_ShowDeleted": @"Показывать удалённые сообщения",
        @"setting.Messages_SaveEditHistory": @"Сохранять историю изменений",
        @"setting.Messages_ShowEditHistory": @"Показывать историю изменений",
        @"setting.Messages_HideBlockedMessages": @"Скрывать сообщения заблокированных",
        @"setting.Messages_HideBlockedReactions": @"Скрывать реакции заблокированных",
        @"setting.Messages_SendTextStyle": @"Стиль отправки текста",
        @"setting.Messages_DeletedPortableReplies": @"Переносимые ответы на удалённые",
        @"setting.Messages_PreserveDeletedMedia": @"Сохранять удалённые медиа",
        @"setting.Messages_DeletedMediaCacheLimit": @"Лимит кэша удалённых медиа",
        @"setting.Messages_DeletedMediaRetentionDays": @"Хранение удалённых медиа (дни)",
        @"setting.Messages_ForwardWithoutAuthor": @"Пересылать без автора",
        @"setting.ProtectedContent_Enabled": @"Инструменты защищённого контента",
        @"setting.ProtectedContent_GalleryShare": @"Отправка из галереи",
        @"setting.ProtectedContent_GallerySave": @"Сохранение из галереи",
        @"setting.ProtectedContent_GalleryCopy": @"Копирование из галереи",
        @"setting.ProtectedContent_ChatSave": @"Сохранение из чата",
        @"setting.ProtectedContent_ChatCopy": @"Копирование из чата",
        @"setting.ProtectedContent_ChatForward": @"Пересылка из чата",
        @"setting.ProtectedContent_AllowScreenshots": @"Разрешать снимки экрана",
        @"setting.ProtectedContent_AllowScreenRecording": @"Разрешать запись экрана",
        @"setting.ProtectedContent_OneTimeScreenshots": @"Снимки одноразовых медиа",
        @"setting.ProtectedContent_OneTimeScreenRecording": @"Запись экрана одноразовых медиа",
        @"setting.ProtectedContent_OneTimeSave": @"Сохранять одноразовые медиа",
        @"setting.Stories_Save": @"Сохранять истории",
        @"setting.Profile_Enabled": @"Расширения профиля",
        @"setting.Profile_ShowIds": @"Показывать ID",
        @"setting.Profile_ShowDCs": @"Показывать DC",
        @"setting.Profile_ShowRegistration": @"Показывать сведения о регистрации",
        @"setting.Appearance_ShowRamUnderClock": @"Показывать RAM под часами",
        @"setting.Appearance_MessageSeconds": @"Показывать секунды сообщений",
        @"setting.Appearance_HideOwnPhone": @"Скрывать свой номер телефона",
        @"setting.Glass_Enabled": @"Стеклянный интерфейс",
        @"setting.ProfileBlur_Avatar": @"Фон профиля из аватара",
        @"setting.ProfileBlur_Animated": @"Анимированный фон профиля",
        @"setting.ProfileBlur_Tint": @"Тонировка фона профиля",
        @"setting.ProfileBlur_Reduced": @"Уменьшенное размытие профиля",
        @"setting.Stars_LocalBalance_Enabled": @"Локальный баланс Stars",
        @"setting.Stars_LocalBalance_Amount": @"Локальное количество Stars",
        @"setting.Stars_LocalBalance_BaseAmount": @"Базовое количество Stars",
        @"setting.global_DownloadBoost": @"Ускорение загрузки",
    }; }); return table;
}
NSString *JGLanguageCode(void) {
    NSArray<NSString *> *candidates = NSBundle.mainBundle.preferredLocalizations;
    NSString *language = candidates.firstObject ?: NSLocale.preferredLanguages.firstObject ?: @"en";
    return [[language lowercaseString] hasPrefix:@"ru"] ? @"ru" : @"en";
}
NSString *JGString(NSString *key) {
    NSDictionary *table = [JGLanguageCode() isEqualToString:@"ru"] ? JGRussianStrings() : JGEnglishStrings();
    return table[key] ?: JGEnglishStrings()[key] ?: key;
}
