#import "JGStrings.h"

static NSString *JGForcedLanguage = nil;

static NSDictionary<NSString *, NSString *> *JGEnglishStrings(void) {
    static NSDictionary<NSString *, NSString *> *table;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{ table = @{
        @"main.jerkgram": @"Jerkgram",
        @"main.ghost": @"Ghost Mode",
        @"main.messages": @"Messages",
        @"main.protected": @"Protected Content",
        @"main.media": @"Media & Stories",
        @"main.appearance": @"Appearance",
        @"main.debug": @"Debug / Research",
        @"main.about": @"About",
        @"page.home": @"Basic Functions",
        @"page.ghost": @"Ghost Mode",
        @"page.messages": @"Messages",
        @"page.protected": @"Protected Content",
        @"page.media": @"Media & Stories",
        @"page.appearance": @"Appearance",
        @"page.debug": @"Debug / Research",
        @"page.about": @"About",
        @"page.stars": @"Stars Balance",
        @"page.data": @"Data and Backup",
        @"page.sendStyle": @"Send Style",
        @"section.profileInformation": @"Profile Card",
        @"profile.information": @"Profile Card",
        @"profile.show": @"Profile Card",
        @"profile.telegramId": @"Show IDs",
        @"profile.avatarDc": @"Show DCs",
        @"profile.registration": @"Registration Date",
        @"section.basicFunctions": @"Basic Functions",
        @"home.stars": @"Stars Balance",
        @"home.dataBackup": @"Data and Backup",
        @"home.backup": @"Backup",
        @"home.local": @"Local",
        @"home.off": @"Off",
        @"ghost.read": @"Don't Mark as Read",
        @"ghost.typing": @"Typing",
        @"ghost.recording": @"Recording",
        @"ghost.uploading": @"Uploading",
        @"ghost.sticker": @"Choosing Sticker",
        @"ghost.game": @"Game Activity",
        @"ghost.emoji": @"Choosing Emoji",
        @"ghost.presence": @"Online Status",
        @"ghost.scheduled": @"Scheduled Send",
        @"messages.deleted.section": @"Deleted Messages",
        @"messages.saveDeleted": @"Save Deleted",
        @"messages.showDeleted": @"Show Deleted Messages",
        @"messages.edits.section": @"Edit History",
        @"messages.saveEdits": @"Save Edit History",
        @"messages.showEdits": @"Show Edit History",
        @"messages.savedDataHint": @"Disabling these features does not remove already saved data.",
        @"messages.text.section": @"Text Sending",
        @"messages.sendStyle": @"Send Style",
        @"messages.sendStyleHint": @"The style is applied after tapping the send button.",
        @"messages.reply.section": @"Deleted Replies",
        @"messages.portableReply": @"Portable Reply",
        @"messages.deletedMedia": @"Save Deleted Media",
        @"messages.portableReplyHint": @"The reply is materialized only after Send. Media is kept only in Jerkgram's internal cache: up to 1 GB for 30 days; if bytes are unavailable, a text fallback is used.",
        @"messages.blocked.section": @"BLOCKED USERS",
        @"messages.hideBlocked": @"Hide Blocked Messages",
        @"messages.hideReactions": @"Hide Blocked Reactions",
        @"style.normal": @"Normal",
        @"style.bold": @"Bold",
        @"style.italic": @"Italic",
        @"style.monospace": @"Monospace",
        @"style.strikethrough": @"Strikethrough",
        @"style.underline": @"Underline",
        @"style.spoiler": @"Spoiler",
        @"style.example.prefix": @"Example: ",
        @"style.example.body": @"this is how your text will look",
        @"protected.enabled": @"Bypass Protection",
        @"protected.galleryShare": @"Share from Gallery",
        @"protected.gallerySave": @"Save from Gallery",
        @"protected.galleryCopy": @"Copy from Gallery",
        @"protected.chatSave": @"Save from Chat",
        @"protected.chatCopy": @"Copy from Chat",
        @"protected.chatForward": @"Forward from Chat",
        @"protected.screenshots": @"Allow Screenshots",
        @"protected.recording": @"Allow Screen Recording",
        @"media.oneTimeScreenshots": @"One-Time Media Screenshots",
        @"media.oneTimeRecording": @"One-Time Media Screen Recording",
        @"media.oneTimeSave": @"Save One-Time Media",
        @"media.storySave": @"Save Stories",
        @"appearance.profile.section": @"Profile Background",
        @"appearance.glass": @"Profile Background Effect",
        @"appearance.avatar": @"Prefer Avatar as Background",
        @"appearance.animated": @"Animated Background",
        @"appearance.tint": @"Color Tint",
        @"appearance.reduced": @"Reduced Blur",
        @"appearance.interface.section": @"Interface",
        @"appearance.seconds": @"Message Seconds",
        @"appearance.hidePhone": @"Hide My Phone Number",
        @"appearance.ram": @"Show RAM Under Clock",
        @"appearance.hidePhoneHint": @"Your phone number is hidden only locally in Jerkgram. Profile editing and number changing remain available.",
        @"debug.copyExtensionDiagnostics": @"Copy Extension Diagnostics",
        @"debug.copied": @"Extension diagnostics copied.",
        @"about.channels.section": @"About",
        @"about.app": @"JerkgramApp",
        @"about.app.subtitle": @"News, builds and updates",
        @"about.community": @"JerkgramCommunity",
        @"about.community.subtitle": @"Community",
        @"about.version.section": @"VERSION",
        @"about.version": @"Jerkgram Version",
        @"about.build": @"Build",
        @"about.telegramBase": @"Telegram Base",
        @"about.privacy.section": @"PRIVACY",
        @"about.analytics": @"Anonymous Analytics",
        @"about.analyticsDescription": @"Help improve Jerkgram by sharing anonymous usage statistics such as Jerkgram version, iOS version and device region. Telegram accounts, messages, usernames and phone numbers are never collected.",
        @"stars.section": @"Stars Balance",
        @"stars.local": @"Local Stars Balance",
        @"stars.change.section": @"Change",
        @"stars.balance": @"Stars Balance",
        @"stars.hint": @"This changes only the local displayed balance. Your real Telegram balance is not modified.",
        @"data.title": @"Data and Backup",
        @"data.retention.section": @"Retention Rules",
        @"data.history": @"Keep History",
        @"data.media": @"Recovered Media Limit",
        @"data.secret": @"Archive Secret Chats",
        @"data.perChat": @"Per-Chat Rules",
        @"data.saveThisChat": @"Save This Chat",
        @"data.cleanup": @"Clean Up Expired Data",
        @"data.backup.section": @"Backup",
        @"data.export": @"Export Jerkgram Archive",
        @"data.import": @"Import Jerkgram Archive",
        @"data.disabled": @"Do Not Save",
        @"data.forever": @"Forever",
        @"data.unlimited": @"Unlimited",
        @"data.warning": @"Forever with no size limit can use all available storage.",
        @"data.7days": @"7 days",
        @"data.30days": @"30 days",
        @"data.90days": @"90 days",
        @"data.250mb": @"250 MB",
        @"data.500mb": @"500 MB",
        @"data.1gb": @"1 GB",
        @"data.2gb": @"2 GB",
        @"data.5gb": @"5 GB",
        @"action.cancel": @"Cancel",
        @"action.done": @"Done",
        @"action.save": @"Save",
        @"action.ok": @"OK",
        @"common.on": @"On",
        @"common.off": @"Off",
    }; });
    return table;
}

static NSDictionary<NSString *, NSString *> *JGRussianStrings(void) {
    static NSDictionary<NSString *, NSString *> *table;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{ table = @{
        @"main.jerkgram": @"Jerkgram",
        @"main.ghost": @"Режим призрака",
        @"main.messages": @"Сообщения",
        @"main.protected": @"Защищённый контент",
        @"main.media": @"Медиа и истории",
        @"main.appearance": @"Оформление",
        @"main.debug": @"Отладка / Исследования",
        @"main.about": @"О Jerkgram",
        @"page.home": @"Основные функции",
        @"page.ghost": @"Режим призрака",
        @"page.messages": @"Сообщения",
        @"page.protected": @"Защищённый контент",
        @"page.media": @"Медиа и истории",
        @"page.appearance": @"Оформление",
        @"page.debug": @"Отладка / Исследования",
        @"page.about": @"О Jerkgram",
        @"page.stars": @"Баланс Stars",
        @"page.data": @"Данные и резервная копия",
        @"page.sendStyle": @"Стиль отправки",
        @"section.profileInformation": @"Карточка профиля",
        @"profile.information": @"Карточка профиля",
        @"profile.show": @"Карточка профиля",
        @"profile.telegramId": @"Показывать ID",
        @"profile.avatarDc": @"Показывать DC",
        @"profile.registration": @"Дата регистрации",
        @"section.basicFunctions": @"Основные функции",
        @"home.stars": @"Баланс Stars",
        @"home.dataBackup": @"Данные и резервная копия",
        @"home.backup": @"Резервная копия",
        @"home.local": @"Локально",
        @"home.off": @"Выключено",
        @"ghost.read": @"Не отмечать прочитанным",
        @"ghost.typing": @"Набор текста",
        @"ghost.recording": @"Запись",
        @"ghost.uploading": @"Загрузка",
        @"ghost.sticker": @"Выбор стикера",
        @"ghost.game": @"Игровая активность",
        @"ghost.emoji": @"Выбор эмодзи",
        @"ghost.presence": @"Онлайн-статус",
        @"ghost.scheduled": @"Отложенная отправка",
        @"messages.deleted.section": @"Удалённые сообщения",
        @"messages.saveDeleted": @"Сохранять удалённые",
        @"messages.showDeleted": @"Показывать удалённые сообщения",
        @"messages.edits.section": @"История изменений",
        @"messages.saveEdits": @"Сохранять историю изменений",
        @"messages.showEdits": @"Показывать историю изменений",
        @"messages.savedDataHint": @"Выключение функций не удаляет уже сохранённые данные.",
        @"messages.text.section": @"Отправка текста",
        @"messages.sendStyle": @"Стиль отправки",
        @"messages.sendStyleHint": @"Стиль применяется после нажатия кнопки отправки.",
        @"messages.reply.section": @"Удалённые ответы",
        @"messages.portableReply": @"Переносимый ответ",
        @"messages.deletedMedia": @"Сохранять удалённые медиа",
        @"messages.portableReplyHint": @"Ответ материализуется только после Send. Медиа хранится только во внутреннем кэше Jerkgram: до 1 ГБ, 30 дней; если bytes недоступны, используется текстовый fallback.",
        @"messages.blocked.section": @"ЗАБЛОКИРОВАННЫЕ",
        @"messages.hideBlocked": @"Скрывать сообщения заблокированных",
        @"messages.hideReactions": @"Скрывать реакции заблокированных",
        @"style.normal": @"Обычный",
        @"style.bold": @"Жирный",
        @"style.italic": @"Курсив",
        @"style.monospace": @"Моноширинный",
        @"style.strikethrough": @"Зачёркнутый",
        @"style.underline": @"Подчёркнутый",
        @"style.spoiler": @"Спойлер",
        @"style.example.prefix": @"Пример: ",
        @"style.example.body": @"так будет выглядеть ваш текст",
        @"protected.enabled": @"Включить обход защиты",
        @"protected.galleryShare": @"Поделиться из галереи",
        @"protected.gallerySave": @"Сохранить из галереи",
        @"protected.galleryCopy": @"Копировать из галереи",
        @"protected.chatSave": @"Сохранить из чата",
        @"protected.chatCopy": @"Копировать из чата",
        @"protected.chatForward": @"Переслать из чата",
        @"protected.screenshots": @"Разрешить скриншоты",
        @"protected.recording": @"Разрешить запись экрана",
        @"media.oneTimeScreenshots": @"Скриншоты одноразовых медиа",
        @"media.oneTimeRecording": @"Запись одноразовых медиа",
        @"media.oneTimeSave": @"Сохранение одноразовых медиа",
        @"media.storySave": @"Сохранение историй",
        @"appearance.profile.section": @"Фон профиля",
        @"appearance.glass": @"Эффект фона профиля",
        @"appearance.avatar": @"Предпочитать аватар как фон",
        @"appearance.animated": @"Анимированный фон",
        @"appearance.tint": @"Цветовой оттенок",
        @"appearance.reduced": @"Облегчённое размытие",
        @"appearance.interface.section": @"Интерфейс",
        @"appearance.seconds": @"Секунды в сообщениях",
        @"appearance.hidePhone": @"Скрывать мой номер",
        @"appearance.ram": @"Показывать RAM под часами",
        @"appearance.hidePhoneHint": @"Номер скрывается только локально в интерфейсе Jerkgram. Экран изменения профиля и смены номера остаётся доступен.",
        @"debug.copyExtensionDiagnostics": @"Копировать диагностику расширений",
        @"debug.copied": @"Диагностика расширений скопирована.",
        @"about.channels.section": @"О Jerkgram",
        @"about.app": @"JerkgramApp",
        @"about.app.subtitle": @"Новости, сборки и обновления",
        @"about.community": @"JerkgramCommunity",
        @"about.community.subtitle": @"Сообщество",
        @"about.version.section": @"ВЕРСИЯ",
        @"about.version": @"Версия Jerkgram",
        @"about.build": @"Сборка",
        @"about.telegramBase": @"База Telegram",
        @"about.privacy.section": @"КОНФИДЕНЦИАЛЬНОСТЬ",
        @"about.analytics": @"Анонимная аналитика",
        @"about.analyticsDescription": @"Помогайте улучшать Jerkgram, отправляя анонимную статистику использования: версию Jerkgram, версию iOS и регион устройства. Аккаунты Telegram, сообщения, имена пользователей и номера телефонов никогда не собираются.",
        @"stars.section": @"Баланс Stars",
        @"stars.local": @"Локальный баланс Stars",
        @"stars.change.section": @"Изменить",
        @"stars.balance": @"Баланс Stars",
        @"stars.hint": @"Это только локальное отображение баланса. Реальный баланс Telegram не изменяется.",
        @"data.title": @"Данные и резервная копия",
        @"data.retention.section": @"Правила хранения",
        @"data.history": @"Хранить историю",
        @"data.media": @"Лимит восстановленных медиа",
        @"data.secret": @"Архивировать Secret Chats",
        @"data.perChat": @"Правила по чатам",
        @"data.saveThisChat": @"Сохранять этот чат",
        @"data.cleanup": @"Очистить истёкшие данные",
        @"data.backup.section": @"Резервная копия",
        @"data.export": @"Экспорт архива Jerkgram",
        @"data.import": @"Импорт архива Jerkgram",
        @"data.disabled": @"Не сохранять",
        @"data.forever": @"Бессрочно",
        @"data.unlimited": @"Без лимита",
        @"data.warning": @"Бессрочное хранение без лимита может занять всё свободное место.",
        @"data.7days": @"7 дней",
        @"data.30days": @"30 дней",
        @"data.90days": @"90 дней",
        @"data.250mb": @"250 МБ",
        @"data.500mb": @"500 МБ",
        @"data.1gb": @"1 ГБ",
        @"data.2gb": @"2 ГБ",
        @"data.5gb": @"5 ГБ",
        @"action.cancel": @"Отмена",
        @"action.done": @"Готово",
        @"action.save": @"Сохранить",
        @"action.ok": @"ОК",
        @"common.on": @"Вкл.",
        @"common.off": @"Выкл.",
    }; });
    return table;
}

NSString *JGLanguageCode(void) {
    @synchronized (NSObject.class) {
        if (JGForcedLanguage.length != 0) return JGForcedLanguage;
    }
    NSString *language = NSLocale.preferredLanguages.firstObject.lowercaseString ?: @"en";
    if ([language hasPrefix:@"ru"]) return @"ru";
    return @"en";
}

void JGSetLanguageOverride(NSString *languageCode) {
    @synchronized (NSObject.class) {
        NSString *value = languageCode.lowercaseString;
        JGForcedLanguage = [value hasPrefix:@"ru"] ? @"ru" : ([value hasPrefix:@"en"] ? @"en" : nil);
    }
}

NSString *JGString(NSString *key) {
    NSString *value = [JGLanguageCode() isEqualToString:@"ru"] ? JGRussianStrings()[key] : JGEnglishStrings()[key];
    return value ?: JGEnglishStrings()[key] ?: key;
}
